---

- name: Configure SGroup
  hosts: localhost
  tasks:
    - include_role:
        name: sgroup

- name: Create a EC2 instance
  hosts: localhost
  tasks:
    - include_role:
        name: ec2codedeploy

- name: Configure Code Deploy instances
  hosts: launched
  user: ec2-user
  become: True
  become_method: sudo
  tasks:
    - include_role:
        name: coddep
