---

- name: Configure SGroup
  hosts: localhost
  tasks:
    - include_role:
        name: sgroup


- name: Create a EC2 instance
  hosts: localhost
  tasks:
    - include_role:
        name: ec2

- name: Configure instance
  hosts: launched
  user: ec2-user
  become: True
  become_method: sudo
  tasks:
    - include_role:
        name: web
  
