---

- name: Create role
  iam:
    iam_type: role
    name: "{{ ec2.iamrole }}"
    assume_role_policy_document: "{{ lookup('file','policy.json') }}"
    state: present
    managed_policy:
          - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy
